/***********************************************************************************************************************
*                                                                                                                      *
* ANTIKERNEL v0.1                                                                                                      *
*                                                                                                                      *
* Copyright (c) 2012-2017 Andrew D. Zonenberg                                                                          *
* All rights reserved.                                                                                                 *
*                                                                                                                      *
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the     *
* following conditions are met:                                                                                        *
*                                                                                                                      *
*    * Redistributions of source code must retain the above copyright notice, this list of conditions, and the         *
*      following disclaimer.                                                                                           *
*                                                                                                                      *
*    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the       *
*      following disclaimer in the documentation and/or other materials provided with the distribution.                *
*                                                                                                                      *
*    * Neither the name of the author nor the names of any contributors may be used to endorse or promote products     *
*      derived from this software without specific prior written permission.                                           *
*                                                                                                                      *
* THIS SOFTWARE IS PROVIDED BY THE AUTHORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED   *
* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL *
* THE AUTHORS BE HELD LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES        *
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR       *
* BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT *
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE       *
* POSSIBILITY OF SUCH DAMAGE.                                                                                          *
*                                                                                                                      *
***********************************************************************************************************************/

/**
	@file
	@author Andrew D. Zonenberg
	@brief Implementation of JTAGNOCBridgeInterface
 */
#include "nocbridge.h"
#include "JtagDebugBridge_addresses_enum.h"

using namespace std;

/*
	Generated by the following code snippet (for the ATM HEC polynomial, x^8 + x^2 + x + 1)

	const int poly = 0x107;
	for(int i=0; i<256; i++)
	{
		unsigned int temp = i;
		for(int j=0; j<8; j++)
			temp = (temp << 1) ^ ( (temp & 0x80) ? poly : 0 );
		printf("0x%02x, ", temp & 0xff);
		if( (i & 15) == 15)
			printf("\n");
	}
*/
static const uint8_t g_crc8Table[256] =
{
	//*0    *1    *2    *3    *4    *5    *6    *7    *8    *9    *a    *b    *c    *d    *e    *f
	0x00, 0x07, 0x0e, 0x09, 0x1c, 0x1b, 0x12, 0x15, 0x38, 0x3f, 0x36, 0x31, 0x24, 0x23, 0x2a, 0x2d,	//0*
	0x70, 0x77, 0x7e, 0x79, 0x6c, 0x6b, 0x62, 0x65, 0x48, 0x4f, 0x46, 0x41, 0x54, 0x53, 0x5a, 0x5d,	//1*
	0xe0, 0xe7, 0xee, 0xe9, 0xfc, 0xfb, 0xf2, 0xf5, 0xd8, 0xdf, 0xd6, 0xd1, 0xc4, 0xc3, 0xca, 0xcd,	//2*
	0x90, 0x97, 0x9e, 0x99, 0x8c, 0x8b, 0x82, 0x85, 0xa8, 0xaf, 0xa6, 0xa1, 0xb4, 0xb3, 0xba, 0xbd,	//3*
	0xc7, 0xc0, 0xc9, 0xce, 0xdb, 0xdc, 0xd5, 0xd2, 0xff, 0xf8, 0xf1, 0xf6, 0xe3, 0xe4, 0xed, 0xea,	//4*
	0xb7, 0xb0, 0xb9, 0xbe, 0xab, 0xac, 0xa5, 0xa2, 0x8f, 0x88, 0x81, 0x86, 0x93, 0x94, 0x9d, 0x9a,	//5*
	0x27, 0x20, 0x29, 0x2e, 0x3b, 0x3c, 0x35, 0x32, 0x1f, 0x18, 0x11, 0x16, 0x03, 0x04, 0x0d, 0x0a,	//6*
	0x57, 0x50, 0x59, 0x5e, 0x4b, 0x4c, 0x45, 0x42, 0x6f, 0x68, 0x61, 0x66, 0x73, 0x74, 0x7d, 0x7a,	//7*
	0x89, 0x8e, 0x87, 0x80, 0x95, 0x92, 0x9b, 0x9c, 0xb1, 0xb6, 0xbf, 0xb8, 0xad, 0xaa, 0xa3, 0xa4,	//8*
	0xf9, 0xfe, 0xf7, 0xf0, 0xe5, 0xe2, 0xeb, 0xec, 0xc1, 0xc6, 0xcf, 0xc8, 0xdd, 0xda, 0xd3, 0xd4,	//9*
	0x69, 0x6e, 0x67, 0x60, 0x75, 0x72, 0x7b, 0x7c, 0x51, 0x56, 0x5f, 0x58, 0x4d, 0x4a, 0x43, 0x44,	//a*
	0x19, 0x1e, 0x17, 0x10, 0x05, 0x02, 0x0b, 0x0c, 0x21, 0x26, 0x2f, 0x28, 0x3d, 0x3a, 0x33, 0x34,	//b*
	0x4e, 0x49, 0x40, 0x47, 0x52, 0x55, 0x5c, 0x5b, 0x76, 0x71, 0x78, 0x7f, 0x6a, 0x6d, 0x64, 0x63,	//c*
	0x3e, 0x39, 0x30, 0x37, 0x22, 0x25, 0x2c, 0x2b, 0x06, 0x01, 0x08, 0x0f, 0x1a, 0x1d, 0x14, 0x13,	//d*
	0xae, 0xa9, 0xa0, 0xa7, 0xb2, 0xb5, 0xbc, 0xbb, 0x96, 0x91, 0x98, 0x9f, 0x8a, 0x8d, 0x84, 0x83,	//e*
	0xde, 0xd9, 0xd0, 0xd7, 0xc2, 0xc5, 0xcc, 0xcb, 0xe6, 0xe1, 0xe8, 0xef, 0xfa, 0xfd, 0xf4, 0xf3	//f*
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Construction / destruction

JTAGNOCBridgeInterface::JTAGNOCBridgeInterface(JtagFPGA* pfpga)
	: m_fpga(pfpga)
{
	//Populate free list
	for(unsigned int i = DEBUG_LOW_ADDR; i <= DEBUG_HIGH_ADDR; i++)
		m_freeAddresses.emplace(i);

	//Reset the TAP of our DUT and select USER2 (the actual transfer instruction)
	LogTrace("Initializing JTAG port\n");
	pfpga->ResetToIdle();
	pfpga->SelectUserInstruction(1);

	//Switch to SHIFT-DR but don't send any data
	pfpga->EnterShiftDR();

	//Start out sending packets with a zero sequence number
	m_nextSequence = 0;

	//Not ACKing anything yet
	m_acking = 0;
	m_nextAck = 0;
}

JTAGNOCBridgeInterface::~JTAGNOCBridgeInterface()
{
	m_fpga->ResetToIdle();
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Address allocation

bool JTAGNOCBridgeInterface::AllocateClientAddress(uint16_t& addr)
{
	//Pop free list, if we have anything there
	if(m_freeAddresses.empty())
		return false;

	addr = *m_freeAddresses.begin();
	m_freeAddresses.erase(addr);

	return true;
}

void JTAGNOCBridgeInterface::FreeClientAddress(uint16_t addr)
{
	//Disable "comparison is always false due to limited range of data type" warnings for here
	//If DEBUG_*_ADDR are at the low/high ends of the address range some comparisons are pointless
	//but we need them there to keep the code generic.
	#pragma GCC diagnostic push
	#pragma GCC diagnostic ignored "-Wtype-limits"

	//Warn if we try to do something stupid
	if( (addr < DEBUG_LOW_ADDR) || (addr > DEBUG_HIGH_ADDR) )
	{
		LogWarning("JTAGNOCBridgeInterface: Attempted to free client address %04x, which isn't in the debug subnet\n",
			addr);
		return;
	}

	#pragma GCC diagnostic pop

	//If it's already free, something is funky
	if(m_freeAddresses.find(addr) != m_freeAddresses.end())
	{
		LogWarning("JTAGNOCBridgeInterface: Attempted to free client address %04x, which was already free\n",
			addr);
		return;
	}

	//Nope, we're good
	m_freeAddresses.emplace(addr);
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// The actual JTAG bridge stuff

/**
	@brief Cycle the JTAG interface with more data

	Push any pending messages to the DUT; send idles if we have nothing to send.
	Take any returned data and put it in our queue.
 */
void JTAGNOCBridgeInterface::Cycle()
{
	//Send up to 4KB (1K words) of data.
	//Note that some of this may be idle frames rather than actual data if there's nothing to send
	//const int tx_buf_len = 1024;

	//Shrink window size for testing
	const int tx_buf_len = 32;

	//TODO: we do NOT want to clear these buffers! Make them member variables and process stuff statefully
	//so that messages can span multiple Cycle() calls

	//Generate an idle frame we can fill empty space in the TX buffer with
	//TODO: Send different data once link is up!
	AntikernelJTAGFrameHeader idle_frame;
	idle_frame.bits.ack = m_acking;				//Might be ACKing packets
	idle_frame.bits.nak = 0;					//not nacking anything
	idle_frame.bits.credits = 0x3FF;			//we have no limit on buffer space, always report "max"
	idle_frame.bits.ack_seq = m_nextAck;		//ACK number
	idle_frame.bits.payload_present = 0;		//no payload
	idle_frame.bits.rpc = 0;					//no RPC payload
	idle_frame.bits.dma = 0;					//no DMA payload
	idle_frame.bits.length = 0;					//empty payload
	idle_frame.bits.reserved_zero = 0;			//nothing here

	//TODO: Send actual messages here

	//TODO: retransmit logic etc

	//Pad the buffer out to size with idle frames
	LogTrace("Sending stuff...\n");
	while(m_txBuffer.size() <= (tx_buf_len - 2) )
	{
		//Sequence number changes for each packet
		idle_frame.bits.sequence = m_nextSequence;	//Sequence number of the outbound packet
		m_nextSequence = NextSeq(m_nextSequence);

		//TODO: Send proper NAKs:
		//One NAK with sequence number of the bad packet
		//then ACK with sequence number of the last good packet (if any)

		//Update the CRC for the new headers
		ComputeHeaderChecksum(idle_frame);

		//Save packet
		m_txBuffer.push_back(idle_frame.words[0]);
		m_txBuffer.push_back(idle_frame.words[1]);

		//only print first few
		if(m_txBuffer.size() < 64)
			PrintMessageHeader(idle_frame);

		//DEBUG: Send an RPC message after the first few idles
		if(m_txBuffer.size() == 8)
		{
			//Send a single RPC message
			AntikernelJTAGFrameHeader rpc_frame;
			rpc_frame.bits.ack = m_acking;
			rpc_frame.bits.nak = 0;
			rpc_frame.bits.credits = 0x3ff;
			rpc_frame.bits.ack_seq = m_nextAck;
			rpc_frame.bits.payload_present = 1;
			rpc_frame.bits.rpc = 1;
			rpc_frame.bits.dma = 0;
			rpc_frame.bits.length = 4;
			rpc_frame.bits.reserved_zero = 0;
			rpc_frame.bits.sequence = m_nextSequence;		//Sequence number of the outbound packet
			m_nextSequence = NextSeq(m_nextSequence);
			ComputeHeaderChecksum(rpc_frame);
			PrintMessageHeader(rpc_frame);
			m_txBuffer.push_back(rpc_frame.words[0]);		//header
			m_txBuffer.push_back(rpc_frame.words[1]);
			m_txBuffer.push_back(0x11111111);				//data
			m_txBuffer.push_back(0x22222222);
			m_txBuffer.push_back(0x33333333);
			m_txBuffer.push_back(0x44444444);
			m_txBuffer.push_back(0xcccccccc);				//crc32 of data (TODO compute)
		}
	}

	//Input/output data buffers (must be contiguous memory!)
	vector<uint32_t> tx_buf;
	vector<uint32_t> rx_buf;
	tx_buf.reserve(m_txBuffer.size());
	rx_buf.resize(m_txBuffer.size());

	//Append our pending outbox data
	for(auto b : m_txBuffer)
		tx_buf.push_back(b);
	m_txBuffer.clear();

	//Send the actual data
	//TODO: do split transactions
	m_fpga->ShiftData((unsigned char*)&tx_buf[0], (unsigned char*)&rx_buf[0], tx_buf.size() * 32);

	//Append the new data to our existing RX buffer
	for(auto b : rx_buf)
		m_rxBuffer.push_back(b);

	//Process the RX buffer
	LogTrace("Got %d words (%d)\n", (int)rx_buf.size(), (int)m_rxBuffer.size());
	int i = 0;
	while(m_rxBuffer.size() > 1)
	{
		AntikernelJTAGFrameHeader msg;
		msg.words[0] = *m_rxBuffer.begin();
		m_rxBuffer.pop_front();
		msg.words[1] = *m_rxBuffer.begin();
		m_rxBuffer.pop_front();

		//TODO: We need to reset link if this happens, handle it properly!
		if(!VerifyHeaderChecksum(msg))
		{
			LogError("Bad header CRC (at offset %d in buffer)\n", i);
			//break;
		}

		//debug print
		if(i++ < 63)
			PrintMessageHeader(msg);

		//Process payload, if we have it
		if(msg.bits.payload_present)
		{
			//Do we have the full payload?
			//If not, push the headers back onto the start of the buffer and stop.
			if(m_rxBuffer.size() < msg.bits.length)
			{
				LogTrace("Need moar payload\n");
				m_rxBuffer.push_front(msg.words[1]);
				m_rxBuffer.push_front(msg.words[0]);
				break;
			}

			//We have the payload, crunch it
			//For now throw it away
			//TODO: CRC it and do something useful
			for(int i=0; i<msg.bits.length; i++)
			{
				LogTrace("%08x\n", *m_rxBuffer.begin());
				m_rxBuffer.pop_front();
			}
		}

		//If we get here the message was properly verified!
		//Bump the ACK number
		m_acking = true;
		m_nextAck = msg.bits.sequence;
	}
}

/**
	@brief Print out a message
 */
void JTAGNOCBridgeInterface::PrintMessageHeader(const AntikernelJTAGFrameHeader& header)
{
	LogTrace("    %08x %08x: ack = %d, nak = %d, seq = %d, nack = %d, credits=%d, payload = %d, len=%d\n",
		header.words[0],
		header.words[1],
		header.bits.ack,
		header.bits.nak,
		header.bits.sequence,
		header.bits.ack_seq,
		header.bits.credits,
		header.bits.payload_present,
		header.bits.length
		);
}

/**
	@brief Calculate the header CRC for an outbound packet
 */
void JTAGNOCBridgeInterface::ComputeHeaderChecksum(AntikernelJTAGFrameHeader& header)
{
	header.bits.header_checksum = CRC8(header.words, 7);
}

/**
	@brief Make sure an inbound packet has a good header CRC
 */
bool JTAGNOCBridgeInterface::VerifyHeaderChecksum(AntikernelJTAGFrameHeader header)
{
	uint8_t expected = CRC8(header.words, 7);
	uint8_t actual = header.bits.header_checksum;
	bool ok = (expected == actual);
	if(!ok)
		LogTrace("expected: %02x, actual: %02x\n", expected, actual);
	return ok;
}

/**
	@brief Checksums a buffer of data in network byte order
 */
uint8_t JTAGNOCBridgeInterface::CRC8(uint32_t* data, unsigned int len)
{
	uint8_t crc = 0x00;
	for(unsigned int i=0; i<len; i += 4)
	{
		uint32_t d = data[i/4];
		for(unsigned int j=i; j < len && j < (i+4); j++)
		{
			uint8_t b = (d >> 24) & 0xff;
			crc = g_crc8Table[crc ^ b];
			d <<= 8;
		}
	}
	return crc;
}
